# Generated by Django 4.1 on 2023-05-22 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('club_name', models.CharField(max_length=50)),
                ('club_locality', models.CharField(max_length=50)),
                ('club_joined', models.BooleanField(default=False)),
                ('club_members', models.IntegerField(null=True)),
                ('club_presdent', models.CharField(max_length=50)),
                ('club_desc', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('email_token', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('event_name', models.CharField(max_length=40)),
                ('event_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clubs')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clubs',
            name='club_events',
            field=models.ManyToManyField(related_name='+', to='accounts.events'),
        ),
    ]
