# Generated by Django 4.1 on 2023-05-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='club_events',
            field=models.ManyToManyField(null=True, related_name='+', to='accounts.events'),
        ),
    ]
