# Generated by Django 4.1 on 2023-05-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_clubs_club_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='club_events',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='accounts.events'),
        ),
    ]
