# Generated by Django 4.1 on 2023-05-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_events_event_date_events_event_desc_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserClubs',
        ),
    ]
