# Generated by Django 4.1 on 2023-05-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_joinedclubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinedclubs',
            name='test',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
